# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'TapirBaseBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #cssembed:
        #    jar: %kernel.root_dir%/../vendor/packagist/cssembed-bin/bin/cssembed.jar
        #yui_js:
        #    jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        less: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"
        uglifyjs2:
            bin: %kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss
